PL_MVC/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class DepartamentoController : Controller
    {
        // GET: Departamento
        public ActionResult Index()
        {
            return View();
        }
    }
}

PL_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL_MVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }
    }
}

PL_MVC/Views/Departamento/Form.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Información de departamento</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-row">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Area.IdArea, new { @style = "background-color: gainsboro;border-radius: 8px 8px 0 0;width: 80%;text-align: center;margin: 0;" })
                            @Html.DropDownListFor(model => model.Area.IdArea, new SelectList(Model.Area.Areas, "IdArea", "Nombre"), "Selecciona una area", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Area.IdArea)
                        </div>
                    </div>
                    <div class="form-group" style="display:none">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdDepartamento, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdDepartamento, new { @class = "hidden form-control" })
                            @Html.ValidationMessageFor(model => model.IdDepartamento)
                        </div>
                    </div>
                    <div class="form-group" style="padding: 0px;">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre, new { @style = "background-color: gainsboro;border-radius: 8px 8px 0 0;width: 80%;text-align: center;margin: 0;" })
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" style="margin: 22px;" />
                            @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


@section Scripts
    {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#ddlPais").change(function () {
                $("#ddlEstado").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetEstado")',
                    dataType: 'json',
                    data: { IdPais: $("#ddlPais").val() },
                    success: function (estados) {
                        $("#ddlEstado").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(estados, function (i, estados) {
                            $("#ddlEstado").append('<option value="'
                                + estados.idEstado + '">'
                                + estados.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            })

            $("#ddlEstado").change(function () {
                $("#ddlMunicipio").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetMunicipio")',
                    dataType: 'json',
                    data: { IdEstado: $("#ddlEstado").val() },
                    success: function (municipios) {
                        $("#ddlMunicipio").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(municipios, function (i, municipios) {
                            $("#ddlMunicipio").append('<option value="'
                                + municipios.idMunicipio + '">'
                                + municipios.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            });

            $("#ddlMunicipio").change(function () {
                $("#ddlColonia").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetColonia")',
                    dataType: 'json',
                    data: { IdMunicipio: $("#ddlMunicipio").val() },
                    success: function (colonias) {
                        $("#ddlColonia").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(colonias, function (i, colonias) {
                            $("#ddlColonia").append('<option value="'
                                + colonias.idColonia + '">'
                                + colonias.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            });

            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#ImagenPreview").attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

        })
    </script>
}

PL_MVC/Views/Departamento/GetAll.cshtml
@model ML.Departamento
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de Departamentos</h2>
    <hr />

    <h4>Acciones:</h4>
    <p>Para agregar haga click en el boton verde</p>
    <p>Para editar haga click en boton amarillo</p>
    <p>Para eliminar haga click en el boton rojo</p>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+ Agregar", "Form", "Departamento", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Editar</th>
                        <th style="display: none">Id</th>
                        <th>Nombre</th>
                        <th style="display: none">IdArea</th>
                        <th>Area</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Departamento departamento in Model.Departamentos)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning" href="@Url.Action("Form", "Departamento", new { IdDepartamento = departamento.IdDepartamento })"><i class="bi bi-pencil-square"></i></a></td>
                            <td style="display: none">@departamento.IdDepartamento</td>
                            <td>@departamento.Nombre</td>
                            <td style="display: none">@departamento.Area.IdArea</td>
                            <td>@departamento.Area.Nombre</td>
                            <td class="text-center"><a class="btn btn-danger" href="@Url.Action("Delete", "Departamento", new { IdDepartamento= departamento.IdDepartamento})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-trash3" style="color: mintcream"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PL_MVC/Views/Departamento/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Mensaje:</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Usuarios", "GetAll", "Usuario")</li>
                    <li>@Html.ActionLink("Departamentos", "GetAll", "Departamento")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PL_MVC/Views/Usuario/GetAll.cshtml
@model ML.Usuario

@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de Usuarios</h2>
    <hr />

    <h4>Acciones:</h4>
    <p><em>Para <mark>agregar</mark> haga click en el <mark>botón verde</mark></em></p>
    <p><em>Para <mark>editar</mark> haga click en <mark>botón amarillo</mark></em></p>
    <p><em>Para <mark>eliminar</mark> haga click en el <mark>botón rojo</mark></em></p>

    <div style="float:right">
        @Html.ActionLink("+ Agregar", "Form", "Usuario", htmlAttributes: new { @class = "btn btn-success" })
    </div>


    @using (Html.BeginForm("GetAll", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @placeholder = "Apellido Paterno" })
            </div>
            <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-info" />
            </div>
            <div class="col-md-3"></div>
        </div>
    }

    <hr />

    <div class="row">
        <div class="table-responsive">
            <table id="tableUsuarios" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Editar</th>
                        <th style="display:none">Id</th>
                        <th>Nombre completo</th>
                        <th>Fecha de nacimiento</th>
                        <th>UserName</th>
                        <th>Email</th>
                        <th style="display:none">Password</th>
                        <th>Sexo</th>
                        <th>Teléfono</th>
                        <th>Curp</th>
                        <th>Dirección</th>
                        <th style="display:none">IdRol</th>
                        <th>Rol</th>
                        <th>Status</th>
                        <th></th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Usuario usuario in Model.Usuarios)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning" style="color: mintcream" href="@Url.Action("Form", "Usuario", new { IdUsuario = usuario.IdUsuario })"><i class="bi bi-pencil-square"></i></a></td>
                            <td style="display:none">@usuario.IdUsuario</td>
                            <td>@usuario.Nombre @usuario.ApellidoPaterno @usuario.ApellidoMaterno</td>
                            <td>@usuario.FechaNacimiento</td>
                            <td>@usuario.UserName</td>
                            <td>@usuario.Email</td>
                            <td style="display:none">@usuario.Password</td>
                            <td>@usuario.Sexo</td>
                            <td>@usuario.Telefono Celular: @usuario.Celular</td>
                            <td>@usuario.Curp</td>
                            <td>Calle: @usuario.Direccion.Calle, No.Int: @usuario.Direccion.NumeroInterior, No. Ext: @usuario.Direccion.NumeroExterior, Colonia: @usuario.Direccion.Colonia.Nombre, Municipio: @usuario.Direccion.Colonia.Municipio.Nombre, Estado: @usuario.Direccion.Colonia.Municipio.Estado.Nombre País: @usuario.Direccion.Colonia.Municipio.Estado.Pais.Nombre</td>
                            <td style="display:none">@usuario.Rol.IdRol</td>
                            <td>@usuario.Rol.Nombre</td>
                            @if (usuario.Status)
                            {
                                <td>
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="switchStatusUsuario" checked onchange="ChangeStatus(@usuario.IdUsuario, this)">
                                    </div>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="switchStatusUsuario" onchange="ChangeStatus(@usuario.IdUsuario, this)">
                                    </div>
                                </td>
                            }
                            @if (usuario.Imagen != null)
                            {
                                <td><img src="data:image/*;base64,@usuario.Imagen" style=" height:100px; width:100px; "></td>
                            }
                            else
                            {
                                <td><img src="~/Imagen/UsuarioSinFoto.png" style="height:100px; width:100px;"></td>
                            }
                            <td class="text-center"><a class="btn btn-danger" href="@Url.Action("Delete", "Usuario", new { IdUsuario = usuario.IdUsuario})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-trash3" style="color: mintcream"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tableUsuarios').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        })


        function ChangeStatus(idUsuario, e) {
            var status = e.checked
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CambiarStatus")',
                dataType: 'json',
                data: { idUsuario, status },
                success: { },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }


    </script>
}

PL_MVC/Views/Usuario/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Mensaje:</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>